// Generated by gencpp from file ros_learning/AddTwoints.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_ADDTWOINTS_H
#define ROS_LEARNING_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_learning/AddTwointsRequest.h>
#include <ros_learning/AddTwointsResponse.h>


namespace ros_learning
{

struct AddTwoints
{

typedef AddTwointsRequest Request;
typedef AddTwointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoints
} // namespace ros_learning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_learning::AddTwoints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_learning::AddTwoints&) { return value(); }
};

template<>
struct DataType< ::ros_learning::AddTwoints > {
  static const char* value()
  {
    return "ros_learning/AddTwoints";
  }

  static const char* value(const ::ros_learning::AddTwoints&) { return value(); }
};


// service_traits::MD5Sum< ::ros_learning::AddTwointsRequest> should match 
// service_traits::MD5Sum< ::ros_learning::AddTwoints > 
template<>
struct MD5Sum< ::ros_learning::AddTwointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learning::AddTwoints >::value();
  }
  static const char* value(const ::ros_learning::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learning::AddTwointsRequest> should match 
// service_traits::DataType< ::ros_learning::AddTwoints > 
template<>
struct DataType< ::ros_learning::AddTwointsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_learning::AddTwoints >::value();
  }
  static const char* value(const ::ros_learning::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_learning::AddTwointsResponse> should match 
// service_traits::MD5Sum< ::ros_learning::AddTwoints > 
template<>
struct MD5Sum< ::ros_learning::AddTwointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learning::AddTwoints >::value();
  }
  static const char* value(const ::ros_learning::AddTwointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learning::AddTwointsResponse> should match 
// service_traits::DataType< ::ros_learning::AddTwoints > 
template<>
struct DataType< ::ros_learning::AddTwointsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_learning::AddTwoints >::value();
  }
  static const char* value(const ::ros_learning::AddTwointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_ADDTWOINTS_H
