// Generated by gencpp from file ros_learning/WordCount.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_WORDCOUNT_H
#define ROS_LEARNING_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <ros_learning/WordCountRequest.h>
#include <ros_learning/WordCountResponse.h>


namespace ros_learning
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace ros_learning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_learning::WordCount > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_learning::WordCount&) { return value(); }
};

template<>
struct DataType< ::ros_learning::WordCount > {
  static const char* value()
  {
    return "ros_learning/WordCount";
  }

  static const char* value(const ::ros_learning::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::ros_learning::WordCountRequest> should match 
// service_traits::MD5Sum< ::ros_learning::WordCount > 
template<>
struct MD5Sum< ::ros_learning::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learning::WordCount >::value();
  }
  static const char* value(const ::ros_learning::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learning::WordCountRequest> should match 
// service_traits::DataType< ::ros_learning::WordCount > 
template<>
struct DataType< ::ros_learning::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::ros_learning::WordCount >::value();
  }
  static const char* value(const ::ros_learning::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_learning::WordCountResponse> should match 
// service_traits::MD5Sum< ::ros_learning::WordCount > 
template<>
struct MD5Sum< ::ros_learning::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_learning::WordCount >::value();
  }
  static const char* value(const ::ros_learning::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_learning::WordCountResponse> should match 
// service_traits::DataType< ::ros_learning::WordCount > 
template<>
struct DataType< ::ros_learning::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::ros_learning::WordCount >::value();
  }
  static const char* value(const ::ros_learning::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_WORDCOUNT_H
