# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rvo/Information.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Information(genpy.Message):
  _md5sum = "a69941d7ce3cf8fc435842c1ef18e37d"
  _type = "rvo/Information"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string agent_name

float64 agent_pose_x
float64 agent_pose_y
float64 agent_heading
float64 agent_vel_mag
"""
  __slots__ = ['agent_name','agent_pose_x','agent_pose_y','agent_heading','agent_vel_mag']
  _slot_types = ['string','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       agent_name,agent_pose_x,agent_pose_y,agent_heading,agent_vel_mag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Information, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.agent_name is None:
        self.agent_name = ''
      if self.agent_pose_x is None:
        self.agent_pose_x = 0.
      if self.agent_pose_y is None:
        self.agent_pose_y = 0.
      if self.agent_heading is None:
        self.agent_heading = 0.
      if self.agent_vel_mag is None:
        self.agent_vel_mag = 0.
    else:
      self.agent_name = ''
      self.agent_pose_x = 0.
      self.agent_pose_y = 0.
      self.agent_heading = 0.
      self.agent_vel_mag = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.agent_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.agent_pose_x, _x.agent_pose_y, _x.agent_heading, _x.agent_vel_mag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.agent_name = str[start:end].decode('utf-8')
      else:
        self.agent_name = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.agent_pose_x, _x.agent_pose_y, _x.agent_heading, _x.agent_vel_mag,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.agent_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.agent_pose_x, _x.agent_pose_y, _x.agent_heading, _x.agent_vel_mag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.agent_name = str[start:end].decode('utf-8')
      else:
        self.agent_name = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.agent_pose_x, _x.agent_pose_y, _x.agent_heading, _x.agent_vel_mag,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
